title: Vade Mecum Arkey
description: Vade Mecum pour la reprise du projet arkey apres mon d√©part.
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

